package com.ledvance.domain.bean.command

/**
 * @athor : jason yin
 * Email : j.yin@ledvance.com
 * Created date 2026/3/21 09:31
 * Describe : ModeId
 */
enum class ModeId(val title: String, override val command: Byte) : Command {
    // Base
    AutomaticCycle("1. Automatic cycle", 0x00.toByte()),
    PositiveIllusion("2. Positive Illusion", 0x01.toByte()),
    ReverseIllusion("3. Reverse Illusion", 0x02.toByte()),
    ColorfulEnergy("4. Colorful Energy", 0xD4.toByte()),
    ColorfulJumpingTransformation("5. Colorful Jumping Transformation", 0xC2.toByte()),
    RedGreenBlueJump("6. Red Green Blue Jump", 0xC2.toByte()),
    HuangQingziJumpingTransformation("7. Huang Qingzi Jumping Transformation", 0xC3.toByte()),
    SevenColorStrobeLight("8. Seven color strobe light", 0xC4.toByte()),
    RedGreenBlueStrobeLight("9. Red green blue strobe light", 0xC5.toByte()),
    YellowGreenPurpleFlicker("10. Yellow green purple flicker", 0xC6.toByte()),
    SevenColorGradient("11. Seven color gradient", 0xC7.toByte()),
    RedAndYellowAlternatingGradient("12. Red and yellow alternating gradient", 0xC8.toByte()),
    RedPurpleAlternatingGradient("13. Red purple alternating gradient", 0xC9.toByte()),
    GreenYellowAlternatingGradient("15. Green yellow alternating gradient", 0xCB.toByte()),
    BluePurpleAlternatingGradient("16. Blue purple alternating gradient", 0xCC.toByte()),
    RedRacehorse("17. Red racehorse", 0xCD.toByte()),
    GreenRacehorse("18. Green racehorse", 0xCE.toByte()),
    BlueRacehorse("19. Blue racehorse", 0xCF.toByte()),
    YellowRacehorse("20. Yellow racehorse", 0xD0.toByte()),
    CyanRacehorse("21. Cyan racehorse", 0xD1.toByte()),
    PurpleRacehorse("22. Purple racehorse", 0xD2.toByte()),
    WhiteRacehorse("23. White racehorse", 0xD3.toByte()),
    PositiveRainbowChasingLight("24. Positive Rainbow Chasing Light", 0x4D.toByte()),
    ReverseRainbowChasingLight("25. Reverse Rainbow Chasing Light", 0x4E.toByte()),
    PositiveRedGreenBlueChasingLight("26. Positive red green blue Chasing Light", 0x4F.toByte()),
    ReverseRedGreenBlueChasingLight("27. Reverse red green blue Chasing Light", 0x50.toByte()),
    PositiveYellowCyanPurpleChasingLight("28. Positive yellow cyan purple Chasing Light", 0x51.toByte()),
    ReverseYellowCyanPurpleChasingLight("29. Reverse yellow cyan purple Chasing Light", 0x52.toByte()),
    PositiveColorfulFluttering("30. Positive Colorful Fluttering", 0x53.toByte()),
    ReverseColorfulFluttering("31. Reverse Colorful Fluttering", 0x54.toByte()),
    PositiveRedGreenBlueFluttering("32. Positive red green blue fluttering", 0x55.toByte()),
    ReverseRedGreenBlueFluttering("33. Reverse red green blue fluttering", 0x56.toByte()),
    PositiveYellowCyanPurpleFluttering("34. Positive yellow cyan purple fluttering", 0x57.toByte()),
    ReverseYellowCyanPurpleFluttering("35. Reverse yellow cyan purple fluttering", 0x58.toByte()),
    PositiveRainbowPainting("36. Positive Rainbow Painting", 0xB5.toByte()),
    ReverseRainbowPainting("37. Reverse Rainbow Painting", 0xB6.toByte()),
    PositiveRedGreenBluePainting("38. Positive red green blue painting", 0xB7.toByte()),
    ReverseRedGreenBluePainting("39. Reverse red green blue painting", 0xB8.toByte()),
    PositiveYellowCyanPurplePainting("40. Positive yellow cyan purple painting", 0xB9.toByte()),
    ReverseYellowCyanPurplePainting("41. Reverse yellow cyan purple painting", 0xBA.toByte()),
    ColorfulPaintingClosingCeremony("42. Colorful Painting Closing Ceremony", 0xBB.toByte()),
    ColorfulSaladScreenBrushing("43. Colorful Salad Screen Brushing", 0xBC.toByte()),
    RedGreenBluePaintingClosingCeremony("44. Red green blue painting closing ceremony", 0xBD.toByte()),
    RedGreenBlueSaladScreenBrushing("45. Red green blue salad screen brushing", 0xBE.toByte()),
    YellowCyanPurplePaintingClosingCeremony("46. Yellow cyan purple painting closing ceremony", 0xBF.toByte()),
    YellowCyanPurpleSaladScreenBrushing("47. Yellow cyan purple salad screen brushing", 0xC0.toByte()),

    // 窗帘/闭幕式相关
    ColorfulClosingCeremony("1. Colorful Closing Ceremony", 0x39.toByte()),
    ColorfulCurtainPulling("2. Colorful Curtain Pulling", 0x3A.toByte()),
    RedGreenBlueClosingCeremony("3. Red, Green, and Blue Closing Ceremony", 0x3B.toByte()),
    RedGreenBlueCurtains("4. Red, green, and blue curtains", 0x3C.toByte()),
    HuangQingziClosingCeremony("5. Huang Qingzi Closing Ceremony", 0x3D.toByte()),
    HuangQingziPulledCurtain("6. Huang Qingzi pulled the curtain", 0x3E.toByte()),
    RedClosing("7. Red Closing", 0x3F.toByte()),
    RedCurtainPulling("8. Red Curtain Pulling", 0x40.toByte()),
    GreenClosing("9. Green Closing", 0x41.toByte()),
    GreenCurtainPulling("10. Green Curtain Pulling", 0x42.toByte()),
    BlueClosing("11. Blue Closing", 0x43.toByte()),
    BlueCurtainPulling("12. Blue Curtain Pulling", 0x44.toByte()),
    YellowClosing("13. Yellow Closing", 0x45.toByte()),
    YellowCurtainPulling("14. Yellow Curtain Pulling", 0x46.toByte()),
    CyanClosing("15. Cyan Closing", 0x47.toByte()),
    CyanCurtainPulling("16. Cyan Curtain Pulling", 0x48.toByte()),
    PurpleClosing("17. Purple Closing", 0x49.toByte()),
    PurpleCurtainPulling("18. Purple Curtain Pulling", 0x4A.toByte()),
    WhiteClosing("19. White Closing", 0x4B.toByte()),
    WhiteCurtainPulling("20. White Curtain Pulling", 0x4C.toByte()),

    // 明暗过渡相关
    PositiveSevenColorLightDarkTransition("1. Positive Seven Color Light and Dark Transition", 0x03.toByte()),
    ReverseSevenColorLightDarkTransition("2. Reverse seven color light dark transition", 0x04.toByte()),
    PositiveRedGreenBlueLightDarkTransition("3. Positive red green blue light dark transition", 0x05.toByte()),
    ReverseRedGreenBlueLightDarkTransition("4. Reverse red green blue light dark transition", 0x06.toByte()),
    PositiveYellowCyanPurpleLightDarkTransition("5. Positive yellow cyan purple light dark transition", 0x07.toByte()),
    ReverseYellowCyanPurpleLightDarkTransition("6. Reverse yellow cyan purple light dark transition", 0x08.toByte()),
    PositiveSixColorLightDarkTransitionRed("7. Positive six color light dark transition red", 0x09.toByte()),
    ReverseSixColorLightDarkTransitionRed("8. Reverse six color light dark transition red", 0x0A.toByte()),
    PositiveSixColorLightDarkTransitionGreen("9. Positive six color light dark transition green", 0x0B.toByte()),
    ReverseSixColorLightDarkTransitionGreen("10. Reverse six color light dark transition green", 0x0C.toByte()),
    PositiveSixColorLightDarkTransitionBlue("11. Positive six color light dark transition blue", 0x0D.toByte()),
    ReverseSixColorLightDarkTransitionBlue("12. Reverse six color light dark transition blue", 0x0E.toByte()),
    PositiveSixColorLightDarkTransitionCyan("13. Positive six color light dark transition cyan", 0x0F.toByte()),
    ReverseSixColorLightDarkTransitionCyan("14. Reverse six color light dark transition cyan", 0x10.toByte()),
    PositiveSixColorLightDarkTransitionYellow("15. Positive six color light dark transition yellow", 0x11.toByte()),
    ReverseSixColorLightDarkTransitionYellow("16. Reverse six color light dark transition yellow", 0x12.toByte()),
    PositiveSixColorLightDarkTransitionPurple("17. Positive six color light dark transition purple", 0x13.toByte()),
    ReverseSixColorLightDarkTransitionPurple("18. Reverse six color light dark transition purple", 0x14.toByte()),
    PositiveSixColorLightDarkTransitionWhite("19. Positive six color light dark transition white", 0x15.toByte()),
    ReverseSixColorLightDarkTransitionWhite("20. Reverse six color light dark transition white", 0x16.toByte()),

    // 流水效果相关
    PositiveRainbowFlowingWater("1. Positive Rainbow Flowing Water", 0x27.toByte()),
    ReverseRainbowFlowingWater("2. Reverse Rainbow Flowing Water", 0x28.toByte()),
    ForwardFlowingRedGreenBlueWater("3. Forward flowing red green blue water", 0x29.toByte()),
    ReverseRedGreenBlueFlowingWater("4. Reverse red green blue flowing water", 0x2A.toByte()),
    ForwardFlowingYellowCyanPurpleWater("5. Forward flowing yellow cyan purple water", 0x2B.toByte()),
    ReverseYellowCyanPurpleFlowingWater("6. Reverse yellow cyan purple flowing water", 0x2C.toByte()),
    ForwardFlowingRedGreenWater("7. Forward flowing red green water", 0x2D.toByte()),
    ReverseRedGreenFlowingWater("8. Reverse red green flowing water", 0x2E.toByte()),
    ForwardFlowingGreenBlueWater("9. Forward flowing green blue water", 0x2F.toByte()),
    ReverseGreenBlueFlowingWater("10. Reverse green blue flowing water", 0x30.toByte()),
    ForwardFlowingYellowBlueWater("11. Forward flowing yellow blue water", 0x31.toByte()),
    ReverseYellowBlueFlowingWater("12. Reverse yellow blue flowing water", 0x32.toByte()),
    ForwardFlowingYellowCyanWater("13. Forward flowing yellow cyan water", 0x33.toByte()),
    ReverseYellowCyanFlowingWater("14. Reverse yellow cyan flowing water", 0x34.toByte()),
    ForwardFlowingCyanPurpleWater("15. Forward flowing cyan purple water", 0x35.toByte()),
    ReverseCyanPurpleFlowingWater("16. Reverse cyan purple flowing water", 0x36.toByte()),
    ForwardFlowingBlackWhiteWater("17. Forward flowing black white water", 0x37.toByte()),
    ReverseBlackWhiteFlowingWater("18. Reverse black white flowing water", 0x38.toByte()),

    // 白彩交替流水
    PositiveFlowWhiteRedWhite("1. Positive flow of white, red, and white", 0x8F.toByte()),
    ReverseFlowWhiteRedWhite("2. Reverse flow of white, red, and white", 0x90.toByte()),
    PositiveFlowWhiteGreenWhite("3. Positive flow of white, green, and white", 0x91.toByte()),
    ReverseFlowWhiteGreenWhite("4. Reverse flow of white, green, and white", 0x92.toByte()),
    PositiveFlowWhiteBlueWhite("5. Positive flow of white, blue, and white", 0x93.toByte()),
    ReverseFlowWhiteBlueWhite("6. Reverse flow of white, blue, and white", 0x94.toByte()),
    PositiveFlowWhiteYellowWhite("7. Positive flow of white, yellow, and white", 0x95.toByte()),
    ReverseFlowWhiteYellowWhite("8. Reverse flow of white, yellow, and white", 0x96.toByte()),
    PositiveFlowWhiteCyanWhite("9. Positive flow of white, cyan, and white", 0x97.toByte()),
    ReverseFlowWhiteCyanWhite("10. Reverse flow of white, cyan, and white", 0x98.toByte()),
    PositiveFlowWhitePurpleWhite("11. Positive flow of white, purple, and white", 0x99.toByte()),
    ReverseFlowWhitePurpleWhite("12. Reverse flow of white, purple, and white", 0x9A.toByte()),
    PositiveFlowRedWhiteRed("13. Positive flow of red, white, and red", 0x9B.toByte()),
    ReverseFlowRedWhiteRed("14. Reverse flow of red, white, and red", 0x9C.toByte()),
    PositiveFlowGreenWhiteGreen("15. Positive flow of green, white, and green", 0x9D.toByte()),
    ReverseFlowGreenWhiteGreen("16. Reverse flow of green, white, and green", 0x9E.toByte()),
    PositiveFlowBlueWhiteBlue("17. Positive flow of blue, white, and blue", 0x9F.toByte()),
    ReverseFlowBlueWhiteBlue("18. Reverse flow of blue, white, and blue", 0xA0.toByte()),
    PositiveFlowYellowWhiteYellow("19. Positive flow of yellow, white, and yellow", 0xA1.toByte()),
    ReverseFlowYellowWhiteYellow("20. Reverse flow of yellow, white, and yellow", 0xA2.toByte()),
    PositiveFlowCyanWhiteCyan("21. Positive flow of cyan, white, and cyan", 0xA3.toByte()),
    ReverseFlowCyanWhiteCyan("22. Reverse flow of cyan, white, and cyan", 0xA4.toByte()),
    PositiveFlowPurpleWhitePurple("23. Positive flow of purple, white, and purple", 0xA5.toByte()),
    ReverseFlowPurpleWhitePurple("24. Reverse flow of purple, white, and purple", 0xA6.toByte()),

    // 彩色尾迹
    PositiveRainbowTail("1. Positive Rainbow Tail", 0x17.toByte()),
    ReverseRainbowTail("2. Reverse Rainbow Tail", 0x18.toByte()),
    PositiveRedTail("3. Positive red tail", 0x19.toByte()),
    ReverseRedTail("4. Reverse red tail", 0x1A.toByte()),
    PositiveGreenTail("5. Positive green tail", 0x1B.toByte()),
    ReverseGreenTail("6. Reverse green tail", 0x1C.toByte()),
    PositiveBlueTail("7. Positive blue tail", 0x1D.toByte()),
    ReverseBlueTail("8. Reverse blue tail", 0x1E.toByte()),
    PositiveYellowTail("9. Positive yellow tail", 0x1F.toByte()),
    ReverseYellowTail("10. Reverse yellow tail", 0x20.toByte()),
    PositiveCyanTail("11. Positive cyan tail", 0x21.toByte()),
    ReverseCyanTail("12. Reverse cyan tail", 0x22.toByte()),
    PositivePurpleTail("13. Positive purple tail", 0x23.toByte()),
    ReversePurpleTail("14. Reverse purple tail", 0x24.toByte()),
    PositiveWhiteTail("15. Positive white tail", 0x25.toByte()),
    ReverseWhiteTail("16. Reverse white tail", 0x26.toByte()),

    // 正向跑动效果
    RunningForwardRed("1. Running forward red", 0x59.toByte()),
    RunningForwardGreen("2. Running forward green", 0x5B.toByte()),
    RunningForwardBlue("3. Running forward blue", 0x5D.toByte()),
    RunningForwardYellow("4. Running forward yellow", 0x5F.toByte()),
    RunningForwardCyan("5. Running forward cyan", 0x61.toByte()),
    RunningForwardPurple("6. Running forward purple", 0x63.toByte()),
    RunningForwardWhite("7. Running forward white", 0x65.toByte()),
    RunningForwardSevenColors("8. Running forward seven colors", 0x67.toByte()),
    RunningForwardRedBlueGreen("9. Running forward red blue green", 0x69.toByte()),
    RunningForwardYellowPurpleCyan("10. Running forward yellow purple cyan", 0x6B.toByte()),
    RunningForwardBluePurpleCyanYellow("11. Running forward blue purple cyan yellow", 0x6D.toByte()),
    RunningForwardBlueGreenCyanYellow("12. Running forward blue green cyan yellow", 0x6F.toByte()),
    RunningForwardWhiteBackgroundRedDots("13. Running forward white background red dots", 0x71.toByte()),
    RunningForwardRedBackgroundGreenDots14("14. Running forward red background green dots", 0x73.toByte()),
    RunningForwardGreenBackgroundBlueDots("15. Running forward green background blue dots", 0x75.toByte()),
    RunningForwardBlueBackgroundYellowDots("16. Running forward blue background yellow dots", 0x77.toByte()),
    RunningForwardYellowBackgroundCyanDots17("17. Running forward yellow background cyan dots", 0x79.toByte()),
    RunningForwardCyanBackgroundPurpleDots("18. Running forward cyan background purple dots", 0x7B.toByte()),
    RunningForwardPurpleBackgroundWhiteDots("19. Running forward purple background white dots", 0x7D.toByte()),
    RunningForwardRedBackgroundWhiteDots("20. Running forward red background white dots", 0x7F.toByte()),
    RunningForwardRedBackgroundSevenColors("21. Running forward red background seven colors", 0x81.toByte()),
    RunningForwardGreenBackgroundSevenColors("22. Running forward green background seven colors", 0x83.toByte()),
    RunningForwardBlueBackgroundSevenColors("23. Running forward blue background seven colors", 0x85.toByte()),
    RunningForwardYellowBackgroundSevenColors("24. Running forward yellow background seven colors", 0x87.toByte()),
    RunningForwardCyanBackgroundSevenColors("25. Running forward cyan background seven colors", 0x89.toByte()),
    RunningForwardPurpleBackgroundSevenColors("26. Running forward purple background seven colors", 0x8B.toByte()),
    RunningForwardWhiteBackgroundSevenColors("27. Running forward white background seven colors", 0x8D.toByte()),
    RunningForwardBlueBackgroundGreenDots("28. Running forward blue background green dots", 0xA7.toByte()),
    RunningForwardRedBackgroundGreenDots("29. Running forward red background green dots", 0xA9.toByte()),
    RunningForwardBlueBackgroundRedDots("30. Running forward blue background red dots", 0xAB.toByte()),
    RunningForwardYellowBackgroundCyanDots("31. Running forward yellow background cyan dots", 0xAD.toByte()),
    RunningForwardPurpleBackgroundYellowDots("32. Running forward purple background yellow dots", 0xAF.toByte()),
    RunningForwardYellowBackgroundWhiteDots("33. Running forward yellow background white dots", 0xB1.toByte()),
    RunningForwardWhiteBackgroundYellowDots("34. Running forward white background yellow dots", 0xB3.toByte()),

    // 反向跑动效果
    ReverseRunningRed("1. Reverse running red", 0x5A.toByte()),
    ReverseRunningGreen("2. Reverse running green", 0x5C.toByte()),
    ReverseRunningBlue("3. Reverse running blue", 0x5E.toByte()),
    ReverseRunningYellow("4. Reverse running yellow", 0x60.toByte()),
    ReverseRunningCyan("5. Reverse running cyan", 0x62.toByte()),
    ReverseRunningPurple("6. Reverse running purple", 0x64.toByte()),
    ReverseRunningWhite("7. Reverse running white", 0x66.toByte()),
    ReverseRunningSevenColors("8. Reverse running seven colors", 0x68.toByte()),
    ReverseRunningRedBlueGreen("9. Reverse running red blue green", 0x6A.toByte()),
    ReverseRunningYellowPurpleCyan("10. Reverse running yellow purple cyan", 0x6C.toByte()),
    ReverseRunningBluePurpleCyanYellow("11. Reverse running blue purple cyan yellow", 0x6E.toByte()),
    ReverseRunningBlueGreenCyanYellow("12. Reverse running blue green cyan yellow", 0x70.toByte()),
    ReverseRunningWhiteBackgroundRedDots("13. Reverse running white background red dots", 0x72.toByte()),
    ReverseRunningRedBackgroundGreenDots14("14. Reverse running red background green dots", 0x74.toByte()),
    ReverseRunningGreenBackgroundBlueDots("15. Reverse running green background blue dots", 0x76.toByte()),
    ReverseRunningBlueBackgroundYellowDots("16. Reverse running blue background yellow dots", 0x78.toByte()),
    ReverseRunningYellowBackgroundCyanDots17("17. Reverse running yellow background cyan dots", 0x7A.toByte()),
    ReverseRunningCyanBackgroundPurpleDots("18. Reverse running cyan background purple dots", 0x7C.toByte()),
    ReverseRunningPurpleBackgroundWhiteDots("19. Reverse running purple background white dots", 0x7E.toByte()),
    ReverseRunningRedBackgroundWhiteDots("20. Reverse running red background white dots", 0x80.toByte()),
    ReverseRunningRedBackgroundSevenColors("21. Reverse running red background seven colors", 0x82.toByte()),
    ReverseRunningGreenBackgroundSevenColors("22. Reverse running green background seven colors", 0x84.toByte()),
    ReverseRunningBlueBackgroundSevenColors("23. Reverse running blue background seven colors", 0x86.toByte()),
    ReverseRunningYellowBackgroundSevenColors("24. Reverse running yellow background seven colors", 0x88.toByte()),
    ReverseRunningCyanBackgroundSevenColors("25. Reverse running cyan background seven colors", 0x8A.toByte()),
    ReverseRunningPurpleBackgroundSevenColors("26. Reverse running purple background seven colors", 0x8C.toByte()),
    ReverseRunningWhiteBackgroundSevenColors("27. Reverse running white background seven colors", 0x8E.toByte()),
    ReverseRunningBlueBackgroundGreenDots("28. Reverse running blue background green dots", 0xA8.toByte()),
    ReverseRunningRedBackgroundGreenDots("29. Reverse running red background green dots", 0xAA.toByte()),
    ReverseRunningBlueBackgroundRedDots("30. Reverse running blue background red dots", 0xAC.toByte()),
    ReverseRunningYellowBackgroundCyanDots("31. Reverse running yellow background cyan dots", 0xAE.toByte()),
    ReverseRunningPurpleBackgroundYellowDots("32. Reverse running purple background yellow dots", 0xB0.toByte()),
    ReverseRunningYellowBackgroundWhiteDots("33. Reverse running yellow background white dots", 0xB2.toByte()),
    ReverseRunningWhiteBackgroundYellowDots("34. Reverse running white background yellow dots", 0xB4.toByte()),

    // 特殊效果/堆叠/过渡
    SpecialSevenColorsOpening25PM("1. Special Seven Colors Opening at 25 PM", 0xD5.toByte()),
    OrangeRedDarkBrightDarkFilteredFlowingWater("2. Orange red dark bright dark filtered flowing water", 0xD6.toByte()),
    YellowGreenDarkBrightDarkFilteredFlowingWater("3. Yellow green dark bright dark filtered flowing water", 0xD7.toByte()),
    GreenDarkBrightDarkFilteredFlowingWater("4. Green dark bright dark filtered flowing water", 0xD8.toByte()),
    CyanBlueDarkBrightDarkFilteredFlowingWater("5. Cyan blue dark bright dark filtered flowing water", 0xD9.toByte()),
    BlueDarkBrightDarkFilteredFlowingWater("6. Blue dark bright dark filtered flowing water", 0xDA.toByte()),
    PurpleDarkBrightDarkFilteredFlowingWater("7. Purple dark bright dark filtered flowing water", 0xDB.toByte()),
    RedDarkBrightDarkFilteredFlowingWater("8. Red dark bright dark filtered flowing water", 0xDC.toByte()),
    SevenColorStacking("9. Seven color stacking", 0xDD.toByte()),
    OrangeStacking("10. Orange stacking", 0xDE.toByte()),
    YellowGreenStacking("11. Yellow green stacking", 0xDF.toByte()),
    GreenStacking("12. Green stacking", 0xE0.toByte()),
    CyanBlueStacking("13. Cyan blue stacking", 0xE1.toByte()),
    BlueStacking("14. Blue stacking", 0xE2.toByte()),
    PurpleStacking("15. Purple stacking", 0xE3.toByte()),
    RedStacking("16. Red stacking", 0xE4.toByte()),
    ColorfulGradient("17. Colorful gradient", 0xE5.toByte()),
    ColorfulTransition("18. Colorful transition", 0xE6.toByte()),
    RedPurpleTransition("19. Red purple transition", 0xE7.toByte()),
    YellowWhiteTransition("20. Yellow white transition", 0xE8.toByte()),
    YellowOrangeTransition("21. Yellow orange transition", 0xE9.toByte());


    companion object {

        fun fromInt(value: Int): ModeId? {
            // 将 Int 转为 Byte（自动截断高位，符合 Byte 取值范围 -128~127）
            val targetByte = value.toByte()
            // 遍历所有枚举项，匹配 command 字节值
            return entries.find { it.command == targetByte }
        }

        // 基本的枚举列表
        val baseItems = listOf(
            AutomaticCycle,
            PositiveIllusion,
            ReverseIllusion,
            ColorfulEnergy,
            ColorfulJumpingTransformation,
            RedGreenBlueJump,
            HuangQingziJumpingTransformation,
            SevenColorStrobeLight,
            RedGreenBlueStrobeLight,
            YellowGreenPurpleFlicker,
            SevenColorGradient,
            RedAndYellowAlternatingGradient,
            RedPurpleAlternatingGradient,
            GreenYellowAlternatingGradient,
            BluePurpleAlternatingGradient,
            RedRacehorse,
            GreenRacehorse,
            BlueRacehorse,
            YellowRacehorse,
            CyanRacehorse,
            PurpleRacehorse,
            WhiteRacehorse,
            PositiveRainbowChasingLight,
            ReverseRainbowChasingLight,
            PositiveRedGreenBlueChasingLight,
            ReverseRedGreenBlueChasingLight,
            PositiveYellowCyanPurpleChasingLight,
            ReverseYellowCyanPurpleChasingLight,
            PositiveColorfulFluttering,
            ReverseColorfulFluttering,
            PositiveRedGreenBlueFluttering,
            ReverseRedGreenBlueFluttering,
            PositiveYellowCyanPurpleFluttering,
            ReverseYellowCyanPurpleFluttering,
            PositiveRainbowPainting,
            ReverseRainbowPainting,
            PositiveRedGreenBluePainting,
            ReverseRedGreenBluePainting,
            PositiveYellowCyanPurplePainting,
            ReverseYellowCyanPurplePainting,
            ColorfulPaintingClosingCeremony,
            ColorfulSaladScreenBrushing,
            RedGreenBluePaintingClosingCeremony,
            RedGreenBlueSaladScreenBrushing,
            YellowCyanPurplePaintingClosingCeremony,
            YellowCyanPurpleSaladScreenBrushing
        )

        // 窗帘/闭幕式对应的枚举列表
        val curtainItems = listOf(
            ColorfulClosingCeremony,
            ColorfulCurtainPulling,
            RedGreenBlueClosingCeremony,
            RedGreenBlueCurtains,
            HuangQingziClosingCeremony,
            HuangQingziPulledCurtain,
            RedClosing,
            RedCurtainPulling,
            GreenClosing,
            GreenCurtainPulling,
            BlueClosing,
            BlueCurtainPulling,
            YellowClosing,
            YellowCurtainPulling,
            CyanClosing,
            CyanCurtainPulling,
            PurpleClosing,
            PurpleCurtainPulling,
            WhiteClosing,
            WhiteCurtainPulling
        )

        // 明暗过渡对应的枚举列表
        val transitionItems = listOf(
            PositiveSevenColorLightDarkTransition,
            ReverseSevenColorLightDarkTransition,
            PositiveRedGreenBlueLightDarkTransition,
            ReverseRedGreenBlueLightDarkTransition,
            PositiveYellowCyanPurpleLightDarkTransition,
            ReverseYellowCyanPurpleLightDarkTransition,
            PositiveSixColorLightDarkTransitionRed,
            ReverseSixColorLightDarkTransitionRed,
            PositiveSixColorLightDarkTransitionGreen,
            ReverseSixColorLightDarkTransitionGreen,
            PositiveSixColorLightDarkTransitionBlue,
            ReverseSixColorLightDarkTransitionBlue,
            PositiveSixColorLightDarkTransitionCyan,
            ReverseSixColorLightDarkTransitionCyan,
            PositiveSixColorLightDarkTransitionYellow,
            ReverseSixColorLightDarkTransitionYellow,
            PositiveSixColorLightDarkTransitionPurple,
            ReverseSixColorLightDarkTransitionPurple,
            PositiveSixColorLightDarkTransitionWhite,
            ReverseSixColorLightDarkTransitionWhite
        )

        // 流水效果对应的枚举列表
        val flowingWaterItems = listOf(
            PositiveRainbowFlowingWater,
            ReverseRainbowFlowingWater,
            ForwardFlowingRedGreenBlueWater,
            ReverseRedGreenBlueFlowingWater,
            ForwardFlowingYellowCyanPurpleWater,
            ReverseYellowCyanPurpleFlowingWater,
            ForwardFlowingRedGreenWater,
            ReverseRedGreenFlowingWater,
            ForwardFlowingGreenBlueWater,
            ReverseGreenBlueFlowingWater,
            ForwardFlowingYellowBlueWater,
            ReverseYellowBlueFlowingWater,
            ForwardFlowingYellowCyanWater,
            ReverseYellowCyanFlowingWater,
            ForwardFlowingCyanPurpleWater,
            ReverseCyanPurpleFlowingWater,
            ForwardFlowingBlackWhiteWater,
            ReverseBlackWhiteFlowingWater
        )

        // 白彩交替流水对应的枚举列表
        val flowItems = listOf(
            PositiveFlowWhiteRedWhite,
            ReverseFlowWhiteRedWhite,
            PositiveFlowWhiteGreenWhite,
            ReverseFlowWhiteGreenWhite,
            PositiveFlowWhiteBlueWhite,
            ReverseFlowWhiteBlueWhite,
            PositiveFlowWhiteYellowWhite,
            ReverseFlowWhiteYellowWhite,
            PositiveFlowWhiteCyanWhite,
            ReverseFlowWhiteCyanWhite,
            PositiveFlowWhitePurpleWhite,
            ReverseFlowWhitePurpleWhite,
            PositiveFlowRedWhiteRed,
            ReverseFlowRedWhiteRed,
            PositiveFlowGreenWhiteGreen,
            ReverseFlowGreenWhiteGreen,
            PositiveFlowBlueWhiteBlue,
            ReverseFlowBlueWhiteBlue,
            PositiveFlowYellowWhiteYellow,
            ReverseFlowYellowWhiteYellow,
            PositiveFlowCyanWhiteCyan,
            ReverseFlowCyanWhiteCyan,
            PositiveFlowPurpleWhitePurple,
            ReverseFlowPurpleWhitePurple
        )

        // 彩色尾迹对应的枚举列表
        val tailItems = listOf(
            PositiveRainbowTail,
            ReverseRainbowTail,
            PositiveRedTail,
            ReverseRedTail,
            PositiveGreenTail,
            ReverseGreenTail,
            PositiveBlueTail,
            ReverseBlueTail,
            PositiveYellowTail,
            ReverseYellowTail,
            PositiveCyanTail,
            ReverseCyanTail,
            PositivePurpleTail,
            ReversePurpleTail,
            PositiveWhiteTail,
            ReverseWhiteTail
        )

        // 正向跑动效果对应的枚举列表
        val runItems = listOf(
            RunningForwardRed,
            RunningForwardGreen,
            RunningForwardBlue,
            RunningForwardYellow,
            RunningForwardCyan,
            RunningForwardPurple,
            RunningForwardWhite,
            RunningForwardSevenColors,
            RunningForwardRedBlueGreen,
            RunningForwardYellowPurpleCyan,
            RunningForwardBluePurpleCyanYellow,
            RunningForwardBlueGreenCyanYellow,
            RunningForwardWhiteBackgroundRedDots,
            RunningForwardRedBackgroundGreenDots14,
            RunningForwardGreenBackgroundBlueDots,
            RunningForwardBlueBackgroundYellowDots,
            RunningForwardYellowBackgroundCyanDots17,
            RunningForwardCyanBackgroundPurpleDots,
            RunningForwardPurpleBackgroundWhiteDots,
            RunningForwardRedBackgroundWhiteDots,
            RunningForwardRedBackgroundSevenColors,
            RunningForwardGreenBackgroundSevenColors,
            RunningForwardBlueBackgroundSevenColors,
            RunningForwardYellowBackgroundSevenColors,
            RunningForwardCyanBackgroundSevenColors,
            RunningForwardPurpleBackgroundSevenColors,
            RunningForwardWhiteBackgroundSevenColors,
            RunningForwardBlueBackgroundGreenDots,
            RunningForwardRedBackgroundGreenDots,
            RunningForwardBlueBackgroundRedDots,
            RunningForwardYellowBackgroundCyanDots,
            RunningForwardPurpleBackgroundYellowDots,
            RunningForwardYellowBackgroundWhiteDots,
            RunningForwardWhiteBackgroundYellowDots
        )

        // 反向跑动效果对应的枚举列表
        val runBackItems = listOf(
            ReverseRunningRed,
            ReverseRunningGreen,
            ReverseRunningBlue,
            ReverseRunningYellow,
            ReverseRunningCyan,
            ReverseRunningPurple,
            ReverseRunningWhite,
            ReverseRunningSevenColors,
            ReverseRunningRedBlueGreen,
            ReverseRunningYellowPurpleCyan,
            ReverseRunningBluePurpleCyanYellow,
            ReverseRunningBlueGreenCyanYellow,
            ReverseRunningWhiteBackgroundRedDots,
            ReverseRunningRedBackgroundGreenDots14,
            ReverseRunningGreenBackgroundBlueDots,
            ReverseRunningBlueBackgroundYellowDots,
            ReverseRunningYellowBackgroundCyanDots17,
            ReverseRunningCyanBackgroundPurpleDots,
            ReverseRunningPurpleBackgroundWhiteDots,
            ReverseRunningRedBackgroundWhiteDots,
            ReverseRunningRedBackgroundSevenColors,
            ReverseRunningGreenBackgroundSevenColors,
            ReverseRunningBlueBackgroundSevenColors,
            ReverseRunningYellowBackgroundSevenColors,
            ReverseRunningCyanBackgroundSevenColors,
            ReverseRunningPurpleBackgroundSevenColors,
            ReverseRunningWhiteBackgroundSevenColors,
            ReverseRunningBlueBackgroundGreenDots,
            ReverseRunningRedBackgroundGreenDots,
            ReverseRunningBlueBackgroundRedDots,
            ReverseRunningYellowBackgroundCyanDots,
            ReverseRunningPurpleBackgroundYellowDots,
            ReverseRunningYellowBackgroundWhiteDots,
            ReverseRunningWhiteBackgroundYellowDots
        )

        // 特殊效果/堆叠/过渡对应的枚举列表
        val otherItems = listOf(
            SpecialSevenColorsOpening25PM,
            OrangeRedDarkBrightDarkFilteredFlowingWater,
            YellowGreenDarkBrightDarkFilteredFlowingWater,
            GreenDarkBrightDarkFilteredFlowingWater,
            CyanBlueDarkBrightDarkFilteredFlowingWater,
            BlueDarkBrightDarkFilteredFlowingWater,
            PurpleDarkBrightDarkFilteredFlowingWater,
            RedDarkBrightDarkFilteredFlowingWater,
            SevenColorStacking,
            OrangeStacking,
            YellowGreenStacking,
            GreenStacking,
            CyanBlueStacking,
            BlueStacking,
            PurpleStacking,
            RedStacking,
            ColorfulGradient,
            ColorfulTransition,
            RedPurpleTransition,
            YellowWhiteTransition,
            YellowOrangeTransition
        )
    }
}
